name: aerc

services:

  api:
    build: ./api
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./api:/app
      - /app/bin
      - /app/include
      - /app/lib
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  dry-farm:
    build: ./dry-farm
    environment:
      - FAST_API_BASE_URL=${FAST_API_BASE_URL}
      - FAST_API_TARGET=${FAST_API_TARGET}
      - FAST_API_VERSION=${FAST_API_VERSION}
    volumes:
      - './dry-farm:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    depends_on:
      -  api
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432


volumes:
  postgres_data:
  