/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApplicationInfo: typeof import('./components/ApplicationInfo.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Dashboard_2: typeof import('./components/Dashboard_2.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBar_2: typeof import('./components/NavBar_2.vue')['default']
    ReportBugButton: typeof import('./components/ReportBugButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
