/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/budget/': RouteRecordInfo<'/budget/', '/budget', Record<never, never>, Record<never, never>>,
    '/budget/index_alt': RouteRecordInfo<'/budget/index_alt', '/budget/index_alt', Record<never, never>, Record<never, never>>,
    '/config/': RouteRecordInfo<'/config/', '/config', Record<never, never>, Record<never, never>>,
    '/dev/EventDrivenTestPanel': RouteRecordInfo<'/dev/EventDrivenTestPanel', '/dev/EventDrivenTestPanel', Record<never, never>, Record<never, never>>,
    '/dev/FieldMappingDebugger': RouteRecordInfo<'/dev/FieldMappingDebugger', '/dev/FieldMappingDebugger', Record<never, never>, Record<never, never>>,
    '/grants/': RouteRecordInfo<'/grants/', '/grants', Record<never, never>, Record<never, never>>,
    '/grants/edit': RouteRecordInfo<'/grants/edit', '/grants/edit', Record<never, never>, Record<never, never>>,
    '/grants/new': RouteRecordInfo<'/grants/new', '/grants/new', Record<never, never>, Record<never, never>>,
    '/grants/steps/guide': RouteRecordInfo<'/grants/steps/guide', '/grants/steps/guide', Record<never, never>, Record<never, never>>,
    '/grants/steps/step0': RouteRecordInfo<'/grants/steps/step0', '/grants/steps/step0', Record<never, never>, Record<never, never>>,
    '/grants/steps/step1': RouteRecordInfo<'/grants/steps/step1', '/grants/steps/step1', Record<never, never>, Record<never, never>>,
    '/grants/steps/step2': RouteRecordInfo<'/grants/steps/step2', '/grants/steps/step2', Record<never, never>, Record<never, never>>,
    '/grants/steps/step3': RouteRecordInfo<'/grants/steps/step3', '/grants/steps/step3', Record<never, never>, Record<never, never>>,
    '/grants/steps/step4': RouteRecordInfo<'/grants/steps/step4', '/grants/steps/step4', Record<never, never>, Record<never, never>>,
    '/grants/steps/step5': RouteRecordInfo<'/grants/steps/step5', '/grants/steps/step5', Record<never, never>, Record<never, never>>,
    '/grants/steps/step6': RouteRecordInfo<'/grants/steps/step6', '/grants/steps/step6', Record<never, never>, Record<never, never>>,
    '/grants/steps/step7': RouteRecordInfo<'/grants/steps/step7', '/grants/steps/step7', Record<never, never>, Record<never, never>>,
    '/grants/steps/step8': RouteRecordInfo<'/grants/steps/step8', '/grants/steps/step8', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/maps/': RouteRecordInfo<'/maps/', '/maps', Record<never, never>, Record<never, never>>,
    '/qualification/': RouteRecordInfo<'/qualification/', '/qualification', Record<never, never>, Record<never, never>>,
    '/statistics/': RouteRecordInfo<'/statistics/', '/statistics', Record<never, never>, Record<never, never>>,
    '/supplies/': RouteRecordInfo<'/supplies/', '/supplies', Record<never, never>, Record<never, never>>,
  }
}
