/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. \u203C\uFE0F DO NOT MODIFY THIS FILE \u203C\uFE0F
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/budget/': RouteRecordInfo<'/budget/', '/budget', Record<never, never>, Record<never, never>>,
    '/budget/index_alt': RouteRecordInfo<'/budget/index_alt', '/budget/index_alt', Record<never, never>, Record<never, never>>,
    '/config/': RouteRecordInfo<'/config/', '/config', Record<never, never>, Record<never, never>>,
    '/grants/': RouteRecordInfo<'/grants/', '/grants', Record<never, never>, Record<never, never>>,
    '/grants/components/step0': RouteRecordInfo<'/grants/components/step0', '/grants/components/step0', Record<never, never>, Record<never, never>>,
    '/grants/components/step1': RouteRecordInfo<'/grants/components/step1', '/grants/components/step1', Record<never, never>, Record<never, never>>,
    '/grants/components/step2': RouteRecordInfo<'/grants/components/step2', '/grants/components/step2', Record<never, never>, Record<never, never>>,
    '/grants/components/step3': RouteRecordInfo<'/grants/components/step3', '/grants/components/step3', Record<never, never>, Record<never, never>>,
    '/grants/components/step3_1': RouteRecordInfo<'/grants/components/step3_1', '/grants/components/step3_1', Record<never, never>, Record<never, never>>,
    '/grants/components/step4': RouteRecordInfo<'/grants/components/step4', '/grants/components/step4', Record<never, never>, Record<never, never>>,
    '/grants/components/step4_1': RouteRecordInfo<'/grants/components/step4_1', '/grants/components/step4_1', Record<never, never>, Record<never, never>>,
    '/grants/components/step5': RouteRecordInfo<'/grants/components/step5', '/grants/components/step5', Record<never, never>, Record<never, never>>,
    '/grants/components/step5_1': RouteRecordInfo<'/grants/components/step5_1', '/grants/components/step5_1', Record<never, never>, Record<never, never>>,
    '/grants/components/step6': RouteRecordInfo<'/grants/components/step6', '/grants/components/step6', Record<never, never>, Record<never, never>>,
    '/grants/components/step6_1': RouteRecordInfo<'/grants/components/step6_1', '/grants/components/step6_1', Record<never, never>, Record<never, never>>,
    '/grants/components/step7': RouteRecordInfo<'/grants/components/step7', '/grants/components/step7', Record<never, never>, Record<never, never>>,
    '/grants/components/step7_1': RouteRecordInfo<'/grants/components/step7_1', '/grants/components/step7_1', Record<never, never>, Record<never, never>>,
    '/grants/components/step8': RouteRecordInfo<'/grants/components/step8', '/grants/components/step8', Record<never, never>, Record<never, never>>,
    '/grants/components/step8_1': RouteRecordInfo<'/grants/components/step8_1', '/grants/components/step8_1', Record<never, never>, Record<never, never>>,
    '/grants/edit': RouteRecordInfo<'/grants/edit', '/grants/edit', Record<never, never>, Record<never, never>>,
    '/grants/edit_1': RouteRecordInfo<'/grants/edit_1', '/grants/edit_1', Record<never, never>, Record<never, never>>,
    '/grants/edit_2': RouteRecordInfo<'/grants/edit_2', '/grants/edit_2', Record<never, never>, Record<never, never>>,
    '/grants/edit_stepper copy': RouteRecordInfo<'/grants/edit_stepper copy', '/grants/edit_stepper copy', Record<never, never>, Record<never, never>>,
    '/grants/new': RouteRecordInfo<'/grants/new', '/grants/new', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/index_1': RouteRecordInfo<'/login/index_1', '/login/index_1', Record<never, never>, Record<never, never>>,
    '/maps/': RouteRecordInfo<'/maps/', '/maps', Record<never, never>, Record<never, never>>,
    '/qualification/': RouteRecordInfo<'/qualification/', '/qualification', Record<never, never>, Record<never, never>>,
    '/statistics/': RouteRecordInfo<'/statistics/', '/statistics', Record<never, never>, Record<never, never>>,
    '/supplies/': RouteRecordInfo<'/supplies/', '/supplies', Record<never, never>, Record<never, never>>,
  }
}
